name: bank_bay
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+10

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # added dependencies ---->>>
  otp_text_field: ^1.1.3
  animated_splash_screen: ^1.3.0
#  flutter_screenutil: ^5.9.0
  get:
  http: ^1.1.0
  cached_network_image:
  pinput: ^3.0.1
  fluttertoast: ^8.2.2
  shimmer: ^3.0.0
  loader_overlay: 2.0.4
  intl:
  image_picker: ^1.0.4
  get_storage: ^2.1.1
  readmore: ^2.2.0
  custom_navigation_bar: ^0.8.2
  dotted_border: ^2.1.0
  flutter_year_picker: ^0.0.1
  month_picker_dialog:
  image_cropper: ^5.0.0
  dropdown_button2: ^2.3.9
  screen_loader: ^4.0.1
  carousel_slider: ^4.2.1
  dotted_dashed_line: ^0.0.3
  weekly_date_picker: ^1.3.2
  url_launcher: ^6.1.5
  lottie:
  flutter_holo_date_picker: ^1.1.2
  flutter_holo_date_picker_widget: ^1.1.2
  percent_indicator: ^4.2.3
  contained_tab_bar_view: ^0.8.0
  pin_code_fields: ^8.0.1
  file_picker: ^6.1.1
  photo_view: ^0.14.0
  share_plus: ^7.2.1
  path_provider: ^2.0.15
  pdf: ^3.3.0
  google_sign_in: ^6.1.1
  firebase_auth:
  firebase_core:
  firebase_messaging:
#  app_settings: ^5.1.1
  firebase_analytics:
  flutter_facebook_auth: ^6.0.2
  flutter_login_facebook: ^1.9.0
  local_auth: ^2.1.8
  timeline_tile: ^2.0.0
  math_expressions: ^2.4.0
  syncfusion_flutter_gauges: ^24.2.3
  flutter_speed_dial: ^7.0.0
  timelines: ^0.1.0
  dio: ^5.4.1
  permission_handler: ^11.0.0
  flutter_file_downloader:
  calendar_date_picker2: ^0.5.2
  internet_connection_checker: ^1.0.0+1
  overlay_support: ^2.1.0
  flutter_local_notifications: ^17.0.0
  flutter_screenutil: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/gif/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
